linux: &linux
   os: linux
   dist: bionic
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      # Note: Passing CONAN_ENV_COMPILER_LIBCXX=libstdc++ (on mac) or CONAN_ENV_COMPILER_LIBCXX=libstdc++11 doesn't work because Conan package tools will override that.

      # 64-bit builds on GCC 7/8/9. GCC 7 is the one listed on the wiki, so build Debug and Release for this one. Only release for GCC 8 and GCC 9
      #- <<: *linux
        #env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release,Debug
      #- <<: *linux
        #env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release
      #- <<: *linux
        #env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release

        ## OSX
      #- <<: *osx
        #osx_image: xcode10.3
        #env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release,Debug
      - <<: *osx
        osx_image: xcode11.4
        env: CONAN_APPLE_CLANG_VERSIONS=11.0 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release,Debug

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
